### ISSUE TITLE
Software License?

### ISSUE THREAD

**Issue by rcarson3** [jonathanhestroffer/XtalMesh#1]
@jonathanhestroffer I just came across your repo after reading your paper in IMMI.  I'm interested in trying the software out on some voxel microstructure data I have as the results from your paper seemed quite promising especially given that the UCSB crew is making use of it. However before I do, I was wondering what software license is this intended to be released under as there currently isn't associated with the repo given the lack of a LICENSE file?

**Comment by jonathanhestroffer** [comment]
Thank you for reaching out to me. I have now released it under MPL2 software license.
