### ISSUE TITLE
Is grain coarsening an expected behaviour?

### ISSUE THREAD

**Issue by hem-28** [jonathanhestroffer/XtalMesh#3]
Hi @jonathanhestroffer 

Interesting work!  After a lot of struggle getting the dependencies installed (Docker is unfortunately not available in my HPC env), I was able to give it a try today. I started of with the provided example. I used the same arguments for both smoother and mesher as provided in the documentation. After smoothening, I notice that the number of grains are reduced to 75 from 85, and the microstructure doesn't quite match. Below an image. 
I do not believe this is expected.

![image](https://user-images.githubusercontent.com/89460629/157424537-f079df77-814e-4020-9ec8-c82cb1cb6885.png)

**Comment by hem-28** [comment]
@jonathanhestroffer  My bad!
I used the provided '.txt'  files  to test the code.
But used the dream3d.json file to create the voxel mesh. The microstructure created by the .json file does not match to microstructure represented by the '.txt' files.
![image](https://user-images.githubusercontent.com/89460629/157436682-25c5c910-97dc-468a-84ca-819bce409797.png)

**Comment by jonathanhestroffer** [comment]
Thank you for reaching out. I am glad it seems to be working for you. As for usage on HPC cluster, I have in the past used 'singularity' installed on an HPC cluster to pull the XtalMesh docker image and run containers there. I will look into this further and document exact steps needed.

**Comment by jonathanhestroffer** [comment]
I made some changes to the code and usage instructions (see README). I have access to an HPC cluster that uses Singularity to work with containers. I have tested the new code on Singularity version 3.5.2.

The only change you will see on your end is now you need to copy relevant scripts over to your work directory along with input files. These include the 2 python scripts and the 2 tet_mesh_l2q scripts.

**Comment by hem-28** [comment]
@jonathanhestroffer  Thanks for taking the trouble in updating README. I unfortunately do not have access to 'singularity'. My system admins are a bit too stringent. But  surely would help others!
